# Generated by Django 5.2.6 on 2025-09-28 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('pricing', models.IntegerField()),
                ('category', models.CharField(choices=[('3-bed', '3-bedroom'), ('2-bed', '2-bedroom'), ('1-bed', '1-bedroom'), ('Single', 'Single Room'), ('Bedsitter', 'Bedsitter')], default='2-bed', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
