services:
  mysql:
    image: mysql:8.0
    container_name: rentals_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - rentals_mysql_data:/var/lib/mysql
    
volumes:
  rentals_mysql_data: