# Generated by Django 5.2.6 on 2025-09-28 13:51

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[accounts.validators.validate_phone_number]),
        ),
    ]
